<a href="https://colab.research.google.com/github/Shahrukh2016/Pytorch_For_Deep_Learning_And_GenerativeAI/blob/main/1_Pytorch_Intorduction_(Creation%2C_Shapes%2C_Datatypes%2C_Operations%2C_Copying%2C_Reshaping%2C_Conversion).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
print(torch.__version__)

2.9.0+cu126


In [2]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


### 1. Creating a Tensor

In [3]:
## using empty
a = torch.empty(size = (2,3))
print(a)

tensor([[1.6816e-44, 0.0000e+00, 6.7719e-19],
        [0.0000e+00, 1.5582e-42, 0.0000e+00]])


In [4]:
## checking datatype of tensor
type(a)

torch.Tensor

In [5]:
## using zeros
torch.zeros(size = (2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [6]:
## using ones
torch.ones(size = (2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [7]:
## using rand
torch.rand(size = (2,3))

tensor([[0.5174, 0.2042, 0.7867],
        [0.1270, 0.5054, 0.3228]])

In [8]:
## using random_seed
torch.manual_seed(50)
torch.rand(size = (2,3))

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [9]:
## Checking seed if we are getting same output from it o  different runs
## using random_seed
torch.manual_seed(50)
torch.rand(size = (2,3))

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [10]:
## using tensor
torch.tensor(data = [[1,2,3], [4,5,6], [7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [11]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### 2. Tensor Shapes

In [12]:
## defining tensor
x = torch.tensor(data = [[1,2,3], [4,5,6], [7,8,9]])
x.shape

torch.Size([3, 3])

In [13]:
## to create a same shaped tensor with different values
torch.empty_like(x)

tensor([[              0,       558720800,       530193312],
        [135020530998304,               2,               3],
        [              3,               0,               0]])

In [14]:
## to create a same shaped tensor with zeros values
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [15]:
## to create a same shaped tensor with ones values
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [16]:
## to create a same shaped tensor with rand values
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

### 3. Tensor DataType

In [ ]:
## checking dtype
print(x)
print("datatype is: ", x.dtype)

In [ ]:
## assign data type
torch.tensor(data = [1.0,2.0,3.0], dtype = torch.int32)

In [ ]:
## assign data type: vice versa
torch.tensor(data = [1,2,3], dtype = torch.float32)

In [ ]:
## typecasting tensors to different data type
x.to(torch.float32)

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### 4. Mathematical Operations

#### a. Scaler Operation

In [ ]:
## defining new tensor
x = torch.rand(size = (2,3))
x

In [ ]:
# addition
print("addition: ", x + 2)
print("**" * 50)

# substraction
print("substraction: ", x - 2)
print("**" * 50)

# multiplication
print("multiplication: ", x * 3)
print("**" * 50)

# division
print("division: ", x / 3)
print("**" * 50)

# int division
print("int division: ", (x * 100) // 3)
print("**" * 50)

# mod
print("int division: ", ((x * 100)//3) % 2)
print("**" * 50)

# power
print("int division: ", x**2)
print("**" * 50)

#### b. Element wise Operation

In [17]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4605, 0.4877, 0.5927],
        [0.9634, 0.1230, 0.4048]])
tensor([[0.4985, 0.9987, 0.6049],
        [0.5229, 0.6974, 0.2505]])


In [18]:
# add
a + b
# sub
a - b
# multiply
a * b
# division
a / b
# power
a ** b
# mod
a % b

tensor([[0.4605, 0.4877, 0.5927],
        [0.4405, 0.1230, 0.1543]])

In [19]:
## abs
c = torch.tensor(data = [2,-4,-9,10])
print("Initial: ", c)

d = torch.abs(c)
print("Final: ", d)

Initial:  tensor([ 2, -4, -9, 10])
Final:  tensor([ 2,  4,  9, 10])


In [20]:
## negative
c = torch.tensor(data = [2,-4,-9,10])
print("Initial: ", c)

d = torch.neg(c)
print("Final: ", d)

Initial:  tensor([ 2, -4, -9, 10])
Final:  tensor([ -2,   4,   9, -10])


In [23]:
## round
c = torch.tensor(data = [2.23,-4.45,-9.0,10.129])
print("Initial: ", c)

d = torch.round(c)
print("Final: ", d)

Initial:  tensor([ 2.2300, -4.4500, -9.0000, 10.1290])
Final:  tensor([ 2., -4., -9., 10.])


In [24]:
## ceil
c = torch.tensor(data = [2.23,-4.45,-9.0,10.129])
print("Initial: ", c)

d = torch.ceil(c)
print("Final: ", d)

Initial:  tensor([ 2.2300, -4.4500, -9.0000, 10.1290])
Final:  tensor([ 3., -4., -9., 11.])


In [25]:
## floor
c = torch.tensor(data = [2.23,-4.45,-9.0,10.129])
print("Initial: ", c)

d = torch.floor(c)
print("Final: ", d)

Initial:  tensor([ 2.2300, -4.4500, -9.0000, 10.1290])
Final:  tensor([ 2., -5., -9., 10.])


In [27]:
## clamp
c = torch.tensor(data = [2.23,-4.45,-9.0,10.129])
print("Initial: ", c)

d = torch.clamp(c,min= 2, max= 3)
print("Final: ", d)

Initial:  tensor([ 2.2300, -4.4500, -9.0000, 10.1290])
Final:  tensor([2.2300, 2.0000, 2.0000, 3.0000])


#### c. Reduction Operation

In [35]:
## defining tensor
e = torch.randint(size = (2,3), low = 2, high = 5, dtype = torch.float32)
e

tensor([[2., 4., 3.],
        [3., 4., 2.]])

In [36]:
## sum
print("Sum: ",torch.sum(e))

## sum along column
print("Sum along column: ", torch.sum(e, dim = 0))

## sum along rows
print("Sum along rows: ", torch.sum(e, dim = 1))

Sum:  tensor(18.)
Sum along column:  tensor([5., 8., 5.])
Sum along rows:  tensor([9., 9.])


In [37]:
## Mean
print("Mean: ",torch.mean(e))

## Mean along column
print("Mean along column: ", torch.mean(e, dim = 0))

## Mean along rows
print("Mean along rows: ", torch.mean(e, dim = 1))

Mean:  tensor(3.)
Mean along column:  tensor([2.5000, 4.0000, 2.5000])
Mean along rows:  tensor([3., 3.])


In [39]:
## Median
print("Median: ",torch.median(e))

## Median along column
print("Median along column: ", torch.median(e, dim = 0))

## Median along rows
print("Median along rows: ", torch.median(e, dim = 1))

Median:  tensor(3.)
Median along column:  torch.return_types.median(
values=tensor([2., 4., 2.]),
indices=tensor([0, 0, 1]))
Median along rows:  torch.return_types.median(
values=tensor([3., 3.]),
indices=tensor([2, 0]))


In [40]:
## Max and Min
print("Max: ",torch.max(e))
print("Min: ",torch.min(e))

## Max and Min along column
print("Max along column: ", torch.max(e, dim = 0))
print("Min along column: ", torch.min(e, dim = 0))

## Max and Min along rows
print("Max along rows: ", torch.max(e, dim = 1))
print("Min along rows: ", torch.min(e, dim = 1))

Max:  tensor(4.)
Min:  tensor(2.)
Max along column:  torch.return_types.max(
values=tensor([3., 4., 3.]),
indices=tensor([1, 0, 0]))
Min along column:  torch.return_types.min(
values=tensor([2., 4., 2.]),
indices=tensor([0, 0, 1]))
Max along rows:  torch.return_types.max(
values=tensor([4., 4.]),
indices=tensor([1, 1]))
Min along rows:  torch.return_types.min(
values=tensor([2., 2.]),
indices=tensor([0, 2]))


In [41]:
## Product
print("Product: ",torch.prod(e))

## Product along column
print("Product along column: ", torch.prod(e, dim = 0))

## Product along rows
print("Product along rows: ", torch.prod(e, dim = 1))

Product:  tensor(576.)
Product along column:  tensor([ 6., 16.,  6.])
Product along rows:  tensor([24., 24.])


In [42]:
## Variance
print("Variance: ",torch.var(e))

## Variance along column
print("Variance along column: ", torch.var(e, dim = 0))

## Variance along rows
print("Variance along rows: ", torch.var(e, dim = 1))

Variance:  tensor(0.8000)
Variance along column:  tensor([0.5000, 0.0000, 0.5000])
Variance along rows:  tensor([1., 1.])


In [44]:
## Argmax
print("Argmax: ",torch.argmax(e))

Argmax:  tensor(1)


In [45]:
## Argmin
print("Argmin: ",torch.argmin(e))

Argmin:  tensor(0)


#### d. Matrix Multiplication

In [52]:
## defining tensor
m = torch.randint(size = (2,3), low = 2, high = 5)
n = torch.randint(size = (3,2), low = 2, high = 5)

print(m)
print(n)

tensor([[3, 2, 3],
        [2, 2, 2]])
tensor([[3, 2],
        [3, 4],
        [4, 3]])


In [51]:
## matric multiplication
mn = torch.matmul(m,n)
print(mn)

tensor([[21, 26],
        [28, 34]])


#### e. Dot Product

In [54]:
## defining the tensors
vector1 = torch.tensor(data = [1,2,3])
vector2 = torch.tensor(data = [5,6,7])

## dot product
v = torch.dot(vector1, vector2)
print(v)

tensor(38)


In [57]:
## transpose
m = torch.randint(size = (2,3), low = 2, high = 5)
print("Initial: ", m)


m_trans = torch.transpose(m, dim0 = 0, dim1 = 1)
print("Final: ", m_trans)



Initial:  tensor([[2, 3, 4],
        [2, 4, 3]])
Final:  tensor([[2, 2],
        [3, 4],
        [4, 3]])


In [62]:
## determinant
m = torch.randint(size = (3,3), low = 2, high = 5, dtype= torch.float32)
print("Initial: ", m)


m_det = torch.det(m)
print("Final: ", m_det)



Initial:  tensor([[3., 4., 3.],
        [2., 2., 2.],
        [4., 4., 2.]])
Final:  tensor(4.)


In [63]:
## inverse
m = torch.randint(size = (3,3), low = 2, high = 5, dtype= torch.float32)
print("Initial: ", m)


m_inv = torch.det(m)
print("Final: ", m_inv)



Initial:  tensor([[4., 4., 3.],
        [4., 4., 4.],
        [4., 2., 4.]])
Final:  tensor(8.)


#### f. Comparision Operators

In [64]:
## defining tensors
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

print(i)
print(j)

tensor([[9, 1, 4],
        [8, 7, 1]])
tensor([[8, 7, 8],
        [4, 4, 1]])


In [65]:
# greater than
print(i > j)
# less than
print(i < j)
# equal to
print(i == j)
# not equal to
print(i != j)
# greater than equal to
print(i >= j)
# less than equal to
print(i <= j)


tensor([[ True, False, False],
        [ True,  True, False]])
tensor([[False,  True,  True],
        [False, False, False]])
tensor([[False, False, False],
        [False, False,  True]])
tensor([[ True,  True,  True],
        [ True,  True, False]])
tensor([[ True, False, False],
        [ True,  True,  True]])
tensor([[False,  True,  True],
        [False, False,  True]])


#### g. Special Functions

In [72]:
## defining tensor
i = torch.randint(size=(2,3), low=0, high=10, dtype= torch.float32)

print(i)

tensor([[9., 1., 9.],
        [1., 7., 7.]])


In [67]:
## log
i_log = torch.log(i)
print(i_log)

tensor([[1.3863, 1.0986, 0.6931],
        [1.7918, 0.6931, 1.6094]])


In [68]:
## exp
i_exp = torch.exp(i)
print(i_exp)

tensor([[ 54.5981,  20.0855,   7.3891],
        [403.4288,   7.3891, 148.4132]])


In [69]:
## sqrt
i_sqrt = torch.sqrt(i)
print(i_sqrt)

tensor([[2.0000, 1.7321, 1.4142],
        [2.4495, 1.4142, 2.2361]])


In [70]:
## sigmoid
i_sigmoid = torch.sigmoid(i)
print(i_sigmoid)

tensor([[0.9820, 0.9526, 0.8808],
        [0.9975, 0.8808, 0.9933]])


In [74]:
## softmax
i_softmax = torch.softmax(i, dim= 0)
print(i_softmax)

tensor([[9.9966e-01, 2.4726e-03, 8.8080e-01],
        [3.3535e-04, 9.9753e-01, 1.1920e-01]])


In [76]:
## relu
i_relu = torch.relu(i)
print(i_relu)

tensor([[9., 1., 9.],
        [1., 7., 7.]])


### 5. Memory Effective Ways

In [77]:
a = torch.tensor(data = [1,2,3])
b = torch.tensor(data = [4,5,6])

print(a)
print(a)

tensor([1, 2, 3])
tensor([1, 2, 3])


In [82]:
## underscore '_' perform the inplace operation and replaces the mentioned tensor
a.add_(b)

tensor([ 9, 12, 15])

In [83]:
a

tensor([ 9, 12, 15])

### 6. Copying a tensor

In [84]:
a = torch.rand(size = (2,3))
print(a)

tensor([[0.8083, 0.8055, 0.5530],
        [0.0628, 0.9157, 0.4161]])


In [85]:
b = a.clone()

In [86]:
print(a)
print(b)

tensor([[0.8083, 0.8055, 0.5530],
        [0.0628, 0.9157, 0.4161]])
tensor([[0.8083, 0.8055, 0.5530],
        [0.0628, 0.9157, 0.4161]])


In [87]:
a[0][0] = 10

In [88]:
print(a)
print(b)

tensor([[10.0000,  0.8055,  0.5530],
        [ 0.0628,  0.9157,  0.4161]])
tensor([[0.8083, 0.8055, 0.5530],
        [0.0628, 0.9157, 0.4161]])


### 7. Tensors Operation on GPU

In [89]:
torch.cuda.is_available()

True

In [90]:
## creating GPU instance
device = torch.device("cuda")

In [91]:
## creating a new tensor in GPU
a = torch.rand(size = (3,4), device = device)
print(a)

tensor([[0.3146, 0.1458, 0.3482, 0.9447],
        [0.1015, 0.8101, 0.1513, 0.3815],
        [0.9321, 0.0728, 0.4573, 0.6449]], device='cuda:0')


In [95]:
## moving a CPU tensor to GPU
a = torch.rand(size = (3,4))
print("CPU Tensor: ", a)

b = a.to(device=device)
print("GPU Tensor: ", b)

CPU Tensor:  tensor([[0.2651, 0.4249, 0.9888, 0.0682],
        [0.3140, 0.0156, 0.2091, 0.2706],
        [0.9733, 0.3063, 0.8674, 0.4838]])
GPU Tensor:  tensor([[0.2651, 0.4249, 0.9888, 0.0682],
        [0.3140, 0.0156, 0.2091, 0.2706],
        [0.9733, 0.3063, 0.8674, 0.4838]], device='cuda:0')


In [96]:
### Operation Speed Check
import time

# Define the size of the matrices
size = 10000 # Large size for performance comparison

# Create random matrices on CPU
matrix_cpu1 = torch.randn(size, size)
matrix_cpu2 = torch.randn(size, size)

# Measure time on CPU
start_time = time.time()
result_cpu =  torch.matmul(matrix_cpu1, matrix_cpu2)   # Matrix multiplication on CPU
cpu_time = time.time() - start_time

print (f"Time on CPU: {cpu_time:.4f} seconds")

# Move matrices to GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

# Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) # Matrix multiplication on GPU
torch.cuda.synchronize() # Ensure all GPU operations are complete
gpu_time = time.time() - start_time


print(f"Time on GPU: {gpu_time:.4f} seconds")

# Compare results
print("\nSpeedup (CPU time / GPU time):", cpu_time / gpu_time)

Time on CPU: 25.4054 seconds
Time on GPU: 0.6926 seconds

Speedup (CPU time / GPU time): 36.68238226298115


### 8. Reshaping Tensors

In [3]:
a = torch.ones(size = (4,4))
a

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [5]:
## reshape
a.reshape(shape = (2,2,2,2))

tensor([[[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]],


        [[[1., 1.],
          [1., 1.]],

         [[1., 1.],
          [1., 1.]]]])

In [6]:
## flatten
a.flatten()

tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
b = torch.rand(size = (4,2,3))
b

tensor([[[0.3704, 0.9897, 0.6857],
         [0.3533, 0.0619, 0.3930]],

        [[0.2150, 0.9917, 0.0111],
         [0.8070, 0.5860, 0.7946]],

        [[0.0839, 0.8522, 0.7299],
         [0.3352, 0.8800, 0.3086]],

        [[0.6503, 0.9897, 0.7116],
         [0.8849, 0.6696, 0.3819]]])

In [10]:
##permurte
b.permute(1,2,0)

tensor([[[0.3704, 0.2150, 0.0839, 0.6503],
         [0.9897, 0.9917, 0.8522, 0.9897],
         [0.6857, 0.0111, 0.7299, 0.7116]],

        [[0.3533, 0.8070, 0.3352, 0.8849],
         [0.0619, 0.5860, 0.8800, 0.6696],
         [0.3930, 0.7946, 0.3086, 0.3819]]])

In [12]:
## unsqueeze
## image size
c = torch.rand(size = (226,226,3))
c.unsqueeze(dim = 0).shape

torch.Size([1, 226, 226, 3])

In [22]:
## squeeze
d = torch.rand(size = (1,20))
d.squeeze(dim = 0).shape


torch.Size([20])

### 9. NumPy and PyTorch

In [23]:
## importing modules
import numpy as np
import torch

In [24]:
tensor = torch.tensor(data = [1,2,3])
print(type(tensor))

print("**" * 50)

## Tensor to Numpy
numpied_tensor = tensor.numpy()
print(type(numpied_tensor))

<class 'torch.Tensor'>
****************************************************************************************************
<class 'numpy.ndarray'>


In [29]:
array = np.array([1,2,3])
print(type(array))

print("**" * 50)

## Numpy to Tensor
# tensored_numpy = torch.tensor(data = array)
## OR
tensored_numpy = torch.from_numpy(array)

print(type(tensored_numpy))

<class 'numpy.ndarray'>
****************************************************************************************************
<class 'torch.Tensor'>
