<a href="https://colab.research.google.com/github/Shahrukh2016/Pytorch_For_Deep_Learning_And_GenerativeAI/blob/main/1_Pytorch_Intorduction.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import torch
print(torch.__version__)

2.9.0+cu126


In [3]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


### 1. Creating a Tensor

In [5]:
## using empty
a = torch.empty(size = (2,3))
print(a)

tensor([[0., 0., 0.],
        [0., 0., 0.]])


In [6]:
## checking datatype of tensor
type(a)

torch.Tensor

In [7]:
## using zeros
torch.zeros(size = (2,3))

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [8]:
## using ones
torch.ones(size = (2,3))

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [9]:
## using rand
torch.rand(size = (2,3))

tensor([[0.5539, 0.3054, 0.5009],
        [0.9136, 0.7998, 0.0346]])

In [11]:
## using random_seed
torch.manual_seed(50)
torch.rand(size = (2,3))

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [12]:
## Checking seed if we are getting same output from it o  different runs
## using random_seed
torch.manual_seed(50)
torch.rand(size = (2,3))

tensor([[0.6180, 0.0687, 0.3893],
        [0.0404, 0.4013, 0.1442]])

In [13]:
## using tensor
torch.tensor(data = [[1,2,3], [4,5,6], [7,8,9]])

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [15]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10,10))

# using eye
print("using eye ->", torch.eye(5))

# using full
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


### 2. Tensor Shapes

In [16]:
## defining tensor
x = torch.tensor(data = [[1,2,3], [4,5,6], [7,8,9]])
x.shape

torch.Size([3, 3])

In [18]:
## to create a same shaped tensor with different values
torch.empty_like(x)

tensor([[7309453675965983778, 8315168162784306286, 8367752027310484831],
        [7954801838398993778, 2459029315949324647, 3631418863581017443],
        [4121969463035192365, 3257846597507954486, 7003207789164377652]])

In [19]:
## to create a same shaped tensor with zeros values
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [20]:
## to create a same shaped tensor with ones values
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [21]:
## to create a same shaped tensor with rand values
torch.rand_like(x)

NotImplementedError: "check_uniform_bounds" not implemented for 'Long'

### 3. Tensor DataType

In [24]:
## checking dtype
print(x)
print("datatype is: ", x.dtype)

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])
datatype is:  torch.int64


In [26]:
## assign data type
torch.tensor(data = [1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [27]:
## assign data type: vice versa
torch.tensor(data = [1,2,3], dtype = torch.float32)

tensor([1., 2., 3.])

In [29]:
## typecasting tensors to different data type
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.],
        [7., 8., 9.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


### 4. Mathematical Operations

#### a. Scaler Operation

In [31]:
## defining new tensor
x = torch.rand(size = (2,3))
x

tensor([[0.4985, 0.9987, 0.6049],
        [0.5229, 0.6974, 0.2505]])

In [33]:
# addition
print("addition: ", x + 2)
print("**" * 50)

# substraction
print("substraction: ", x - 2)
print("**" * 50)

# multiplication
print("multiplication: ", x * 3)
print("**" * 50)

# division
print("division: ", x / 3)
print("**" * 50)

# int division
print("int division: ", (x * 100) // 3)
print("**" * 50)

# mod
print("int division: ", ((x * 100)//3) % 2)
print("**" * 50)

# power
print("int division: ", x**2)
print("**" * 50)

addition:  tensor([[2.4985, 2.9987, 2.6049],
        [2.5229, 2.6974, 2.2505]])
****************************************************************************************************
substraction:  tensor([[-1.5015, -1.0013, -1.3951],
        [-1.4771, -1.3026, -1.7495]])
****************************************************************************************************
multiplication:  tensor([[1.4954, 2.9962, 1.8146],
        [1.5687, 2.0922, 0.7515]])
****************************************************************************************************
division:  tensor([[0.1662, 0.3329, 0.2016],
        [0.1743, 0.2325, 0.0835]])
****************************************************************************************************
int division:  tensor([[16., 33., 20.],
        [17., 23.,  8.]])
****************************************************************************************************
int division:  tensor([[0., 1., 0.],
        [1., 1., 0.]])
*********************************