<a href="https://colab.research.google.com/github/Shahrukh2016/Pytorch_For_Deep_Learning_And_GenerativeAI/blob/main/3_PyTorch_Training_Pipeline.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
## improting necessary pipeline
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [2]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [3]:
df.shape

(569, 33)

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [5]:
df.sample(5)

id diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
240  88350402         B        13.64         15.60           87.38      575.3   
298    892214         B        14.26         18.17           91.22      633.1   
306     89344         B        13.20         15.82           84.07      537.3   
546    922577         B        10.32         16.35           65.31      324.9   
374   9013005         B        13.69         16.07           87.84      579.1   

     smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
240          0.09423           0.06630        0.047050             0.037310   
298          0.06576           0.05220        0.024750             0.013740   
306          0.08511           0.05251        0.001461             0.003261   
546          0.09434           0.04994        0.010120             0.005495   
374          0.08302           0.06374        0.025560             0.020310   

     ...  texture_worst  perimeter_worst  area_worst  smoothness_worst  \
240  ...          19.05            94.11       683.4           0.12780   
298  ...          25.26           105.80       819.7           0.09445   
306  ...          20.45            92.00       636.9           0.11280   
546  ...          21.77            71.12       384.9           0.12850   
374  ...          20.21            99.16       670.6           0.11050   

     compactness_worst  concavity_worst  concave points_worst  symmetry_worst  \
240            0.12910          0.15330               0.09222          0.2530   
298            0.21670          0.15650               0.07530          0.2636   
306            0.13460          0.01120               0.02500          0.2651   
546            0.08842          0.04384               0.02381          0.2681   
374            0.20960          0.13460               0.06987          0.3323   

     fractal_dimension_worst  Unnamed: 32  
240                  0.06510          NaN  
298                  0.07676          NaN  
306                  0.08385          NaN  
546                  0.07399          NaN  
374                  0.07701          NaN  

[5 rows x 33 columns]

In [6]:
df.drop(columns=["id", "Unnamed: 32"], axis = 0 , inplace=True)
df.head(1)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38           122.8     1001.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.1184            0.2776          0.3001               0.1471   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                   0.1189  

[1 rows x 31 columns]

In [7]:
## segregating values of dependent and independent variable
X = df.drop(columns = ["diagnosis"]).values
y = df.loc[:,"diagnosis"].values

In [8]:
## train test split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455,) (114,)


In [9]:
## Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [10]:
X_train

array([[ 0.44910739, -0.04112038,  0.61097651, ...,  1.46082394,
         2.2074545 ,  1.13353336],
       [-1.32827283,  0.37537627, -1.31381911, ..., -0.73752708,
        -0.03389858,  0.43641005],
       [-0.52654285, -0.81361698, -0.54701396, ..., -0.98977501,
        -0.68318594, -1.13468633],
       ...,
       [ 1.26921918, -0.41806149,  1.29094261, ...,  1.82096639,
         1.47618642,  0.4223486 ],
       [ 1.39647791,  1.60392508,  1.5121364 , ...,  1.02509604,
        -0.96356003,  0.43208345],
       [-0.26919742,  2.01576814, -0.29919499, ..., -0.52396113,
        -0.69794247, -1.06059331]])

In [11]:
y_train

array(['M', 'B', 'B', 'M', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'M',
       'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'B', 'M', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'B', 'M', 'B', 'B', 'B', 'B', 'M',
       'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B', 'M', 'B', 'M', 'B', 'B',
       'B', 'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'B', 'M', 'B', 'M',
       'B', 'M', 'M', 'M', 'B', 'B', 'M', 'B', 'B', 'B', 'M', 'B', 'M',
       'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B',
       'B', 'M', 'M', 'B', 'B', 'B', 'B', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'M', 'B', 'B', 'B', 'B', 'M', 'B', 'B', 'B', 'B', 'B', 'B',
       'B', 'B', 'B', 'M', 'B', 'M', 'M', 'B', 'B', 'B', 'M', 'B', 'B',
       'B', 'B', 'B', 'B', 'B', 'M', 'M', 'M', 'M', 'M', 'M', 'B', 'M',
       'M', 'B', 'M', 'M', 'M', 'B', 'M', 'B', 'B', 'M', 'M', 'B

In [12]:
## Since out tagert variable contains string (category), we need to impute it using LabelEncoder
# LabelEncoder

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [13]:
y_test

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1])

In [14]:
## Converting numpy arrays to tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

## checking
print(type(X_train_tensor))
print(type(X_test_tensor))
print(type(y_train_tensor))
print(type(y_test_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


#### Defining the model

In [15]:
class MySimpleNN():

  def __init__(self, X):

    self.weights = torch.rand(X.shape[1], 1, dtype = torch.float64, requires_grad = True)
    self.bias = torch.zeros(1, dtype = torch.float64, requires_grad = True)

  def forward(self,X):

    z = torch.matmul(X, self.weights) + self.bias
    y_pred = torch.sigmoid(z)
    return y_pred

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

#### Important Parameters

In [22]:
learning_rate = 0.1
epochs = 75

### Training Pipeline

In [23]:
## create model
model = MySimpleNN(X_train_tensor)
# print(model.weights)
# print(model.bias)

##define loop
for epoch in range(epochs):

  ## forward pass
  y_pred = model.forward(X = X_train_tensor)
  # print(y_pred)

  ## calculate loss
  loss = model.loss_function(y_pred = y_pred, y = y_train_tensor)

  ## backward pass
  loss.backward()

  ## parameters update
  with torch.no_grad():
    model.weights -= (learning_rate * model.weights.grad)
    model.bias -= (learning_rate * model.bias.grad)

  ## zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  ## print loss in each epoch
  print(f'Epoch: {epoch + 1}, Loss: {loss.item()}')


Epoch: 1, Loss: 4.26761523352235
Epoch: 2, Loss: 4.169414470437044
Epoch: 3, Loss: 4.069211587939508
Epoch: 4, Loss: 3.964014506269813
Epoch: 5, Loss: 3.8547849127900293
Epoch: 6, Loss: 3.7436789240712836
Epoch: 7, Loss: 3.623735780109451
Epoch: 8, Loss: 3.499918017698361
Epoch: 9, Loss: 3.3709008934036904
Epoch: 10, Loss: 3.2341828297870867
Epoch: 11, Loss: 3.0932625493823998
Epoch: 12, Loss: 2.950409676949142
Epoch: 13, Loss: 2.805455545882459
Epoch: 14, Loss: 2.6543333102899376
Epoch: 15, Loss: 2.494773228009194
Epoch: 16, Loss: 2.3311196253651727
Epoch: 17, Loss: 2.160970823922075
Epoch: 18, Loss: 1.9916604919971912
Epoch: 19, Loss: 1.826218732389162
Epoch: 20, Loss: 1.668775323006408
Epoch: 21, Loss: 1.5202636466013453
Epoch: 22, Loss: 1.379359386720328
Epoch: 23, Loss: 1.251776642998912
Epoch: 24, Loss: 1.1424372214993441
Epoch: 25, Loss: 1.0518656560339394
Epoch: 26, Loss: 0.9795044763945417
Epoch: 27, Loss: 0.9237669224343529
Epoch: 28, Loss: 0.8822293180370587
Epoch: 29, Loss:

### Evaluate

In [24]:
## model evaluation
with torch.no_grad():
  y_pred = model.forward(X_test_tensor)
  y_pred = (y_pred > 0.5).float()
  print(y_pred)

tensor([[0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
      

In [21]:
from sklearn.metrics import accuracy_score
accuracy_score(y_true = y_test_tensor, y_pred = y_pred)

0.631578947368421