<a href="https://colab.research.google.com/github/Shahrukh2016/Pytorch_For_Deep_Learning_And_GenerativeAI/blob/main/4_PyTorch_Training_Pipeline_Using_NN_Module.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Single neuron model

first layer: 5 neuron\
second layer: 1 sigmoid

In [1]:
## create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid(out)

    return out

In [2]:
## create dataset
features = torch.rand(size = (10,5))

## create model
model = Model(num_features= features.shape[1])

## calling model
model(features)

tensor([[0.4464],
        [0.5142],
        [0.5025],
        [0.4940],
        [0.5227],
        [0.4841],
        [0.5695],
        [0.5064],
        [0.4723],
        [0.4586]], grad_fn=<SigmoidBackward0>)

In [3]:
## show model weights and bias
print(model.linear.weight)
print(model.linear.bias)

Parameter containing:
tensor([[-0.0473, -0.0886, -0.0596,  0.2727, -0.3333]], requires_grad=True)
Parameter containing:
tensor([0.1474], requires_grad=True)


In [4]:
!pip install torchinfo

In [5]:
## visualizing the NN
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Multi neuron model:

first layer: 5 neuron\
second layer: 3 neuron\
third layer: 1 sigmoid

In [6]:
## create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear1 = nn.Linear(num_features, 3)
    self.relu = nn.ReLU()
    self.linear2 = nn.Linear(3, 1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear1(features)
    out = self.relu(out)
    out = self.linear2(out)
    out = self.sigmoid(out)

    return out

In [7]:
## create dataset
features = torch.rand(size = (10,5))

## create model
model = Model(num_features= features.shape[1])

## calling model
model(features)

tensor([[0.4954],
        [0.5187],
        [0.4854],
        [0.5123],
        [0.5245],
        [0.5263],
        [0.5234],
        [0.5185],
        [0.5162],
        [0.5227]], grad_fn=<SigmoidBackward0>)

In [8]:
## show model weights and bias
print(f'Linear 1: {model.linear1.weight, model.linear1.bias}')
print(f'Linear 2: {model.linear2.weight, model.linear2.bias}')


Linear 1: (Parameter containing:
tensor([[-0.0914, -0.2038, -0.3241,  0.3970,  0.1335],
        [-0.0096, -0.4125,  0.4131,  0.4353, -0.2642],
        [ 0.0434,  0.1354,  0.3102,  0.1808, -0.1844]], requires_grad=True), Parameter containing:
tensor([-0.3680, -0.0623, -0.0090], requires_grad=True))
Linear 2: (Parameter containing:
tensor([[-0.3345, -0.4494,  0.1301]], requires_grad=True), Parameter containing:
tensor([0.0492], requires_grad=True))


In [9]:
## visualizing the NN
from torchinfo import summary

summary(model, input_size = (10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

### Containerization

In [10]:
## create model class
import torch
import torch.nn as nn

class Model(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.network = nn.Sequential(
      nn.Linear(num_features, 3),
      nn.ReLU(),
      nn.Linear(3, 1),
      nn.Sigmoid()
    )

  def forward(self, features):
    out = self.network(features)
    return out

In [11]:
## create dataset
features = torch.rand(size = (10,5))

## create model
model = Model(num_features= features.shape[1])

## calling model
model(features)

tensor([[0.5264],
        [0.4827],
        [0.4847],
        [0.5005],
        [0.5045],
        [0.4921],
        [0.5121],
        [0.5078],
        [0.4846],
        [0.4989]], grad_fn=<SigmoidBackward0>)

### Real World DataSet

In [12]:
## improting necessary pipeline
import numpy as np
import pandas as pd
import torch
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [13]:
df = pd.read_csv('https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv')

In [14]:
df.shape

(569, 33)

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 33 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   id                       569 non-null    int64  
 1   diagnosis                569 non-null    object 
 2   radius_mean              569 non-null    float64
 3   texture_mean             569 non-null    float64
 4   perimeter_mean           569 non-null    float64
 5   area_mean                569 non-null    float64
 6   smoothness_mean          569 non-null    float64
 7   compactness_mean         569 non-null    float64
 8   concavity_mean           569 non-null    float64
 9   concave points_mean      569 non-null    float64
 10  symmetry_mean            569 non-null    float64
 11  fractal_dimension_mean   569 non-null    float64
 12  radius_se                569 non-null    float64
 13  texture_se               569 non-null    float64
 14  perimeter_se             5

In [16]:
df.drop(columns=["id", "Unnamed: 32"], axis = 0 , inplace=True)
df.head(1)

diagnosis  radius_mean  texture_mean  perimeter_mean  area_mean  \
0         M        17.99         10.38           122.8     1001.0   

   smoothness_mean  compactness_mean  concavity_mean  concave points_mean  \
0           0.1184            0.2776          0.3001               0.1471   

   symmetry_mean  ...  radius_worst  texture_worst  perimeter_worst  \
0         0.2419  ...         25.38          17.33            184.6   

   area_worst  smoothness_worst  compactness_worst  concavity_worst  \
0      2019.0            0.1622             0.6656           0.7119   

   concave points_worst  symmetry_worst  fractal_dimension_worst  
0                0.2654          0.4601                   0.1189  

[1 rows x 31 columns]

In [17]:
## segregating values of dependent and independent variable
X = df.drop(columns = ["diagnosis"]).values
y = df.loc[:,"diagnosis"].values

In [18]:
## train test split
X_train, X_test, y_train, y_test =  train_test_split(X, y, test_size=0.2)
print(X_train.shape, X_test.shape, y_train.shape, y_test.shape)

(455, 30) (114, 30) (455,) (114,)


In [19]:
## Scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [20]:
## Since out tagert variable contains string (category), we need to impute it using LabelEncoder
# LabelEncoder

encoder = LabelEncoder()
y_train = encoder.fit_transform(y_train)
y_test = encoder.transform(y_test)

In [21]:
## Converting numpy arrays to tensors
X_train_tensor = torch.from_numpy(X_train)
X_test_tensor = torch.from_numpy(X_test)
y_train_tensor = torch.from_numpy(y_train)
y_test_tensor = torch.from_numpy(y_test)

## checking
print(type(X_train_tensor))
print(type(X_test_tensor))
print(type(y_train_tensor))
print(type(y_test_tensor))

<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>
<class 'torch.Tensor'>


In [23]:
## Defining the model

class MySimpleNN(nn.Module):

  def __init__(self, num_features):

    super().__init__()
    self.linear = nn.Linear(num_features,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self, features):
    out = self.linear(features)
    out = self.sigmoid()
    return out

  def loss_function(self, y_pred, y):
    # Clamp predictions to avoid log(0)
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)

    # Calculate loss
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred)).mean()
    return loss

In [24]:
learning_rate = 0.1
epochs = 75